version: '3'
services:
  test-db:
    build: .
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - .:/test-db
      - ./backup:/backup
      - test-db:/var/lib/postgresql/data
    shm_size: 192m

volumes:
  test-db:
